import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('artifacts', {recursive:true});
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if(message.type() === 'error') errors.push(message.text()); });
for(const width of [320,390,768,1024,1440]) {
  await page.setViewportSize({width,height:900});
  await page.goto('http://127.0.0.1:5173/');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('h1').count(),1);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true, `Overflow at ${width}`);
  const assets = await page.locator('img').evaluateAll(images => images.filter(image=>image.getBoundingClientRect().width>0).map(image=>({loaded:image.complete && image.naturalWidth>0,width:image.getBoundingClientRect().width,height:image.getBoundingClientRect().height})));
  assert(assets.every(asset=>asset.loaded && asset.width === 24 && asset.height === 24));
  await page.screenshot({path:`artifacts/website-${width}.png`,fullPage:true});
  console.log(`Viewport ${width}: layout and assets passed`);
}
await page.setViewportSize({width:390,height:900});
await page.goto('http://127.0.0.1:5173/');
await page.keyboard.press('Tab');
assert.equal(await page.locator('.skip-link').evaluate(el=>el === document.activeElement),true);
await page.keyboard.press('Enter');
assert.equal(await page.locator('#main').evaluate(el=>el === document.activeElement),true);
const menu=page.getByRole('button',{name:'Mở menu'});
await menu.focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('#mobile-menu').isVisible(),true);
await page.keyboard.press('Escape');
assert.equal(await menu.getAttribute('aria-expanded'),'false');
assert.equal(await menu.evaluate(el=>el === document.activeElement),true);
await menu.click();await page.locator('#mobile-menu').getByRole('link',{name:'Dịch vụ',exact:true}).click();
assert.equal(await page.locator('#mobile-menu').isVisible(),false);
assert(page.url().endsWith('#services'));
await page.getByRole('button',{name:'Gửi email tư vấn →'}).click();
assert.match(await page.getByRole('status').textContent(),/yêu cầu chưa được gửi/);
await page.goto('http://127.0.0.1:5173/missing');
assert.equal(await page.getByRole('heading',{name:'Không tìm thấy trang'}).count(),1);
assert.deepEqual(errors,[]);
console.log('Keyboard, menu, anchors, demo notice, 404, and console passed');
await browser.close();
